confirm_os_window_close 0
background_opacity 0.90
hide_window_decorations no
window_padding_width 8

font_family UbuntuMono Nerd Font
font_size 13.0

modify_font line_height +1px

background            #222222
foreground            #c2c2c2
selection_background  #3b3b3b
selection_foreground  #c2c2c2

cursor                #7e8a7b
cursor_text_color     #222222

color0                #222222
color8                #686868

color1                #685555
color9                #bb6666

color2                #5f875f
color10               #7e8a7b

color3                #87875f
color11               #bba868

color4                #5f8787
color12               #688888

color5                #875f87
color13               #bb6688

color6                #5f8777
color14               #688877

color7                #c2c2c2
color15               #e6e6e6
